name: Deploy Unikernel
on:
  push:
    branches: [master, main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install KraftKit
        run: |
          curl -sSfL https://get.kraftkit.sh | sh
          echo "/home/runner/.kraftkit/bin" >> $GITHUB_PATH

      - name: Build and Deploy to KraftCloud
        env:
          UKC_TOKEN: ${{ secrets.UKC_TOKEN }}
          UKC_METRO: fra
        run: |
          kraft cloud deploy \
            --build \
            --as dockerfile \
            --name hello-unikraft \
            --project . \
            --wait 10s \
            --scale-to-zero on
